export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';
export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';

export const FETCH_TOP_ITEMS_SUCCESS = 'FETCH_TOP_ITEMS_SUCCESS';
export const FETCH_TOP_ITEMS_FAILURE = 'FETCH_TOP_ITEMS_FAILURE';
export const FETCH_TOP_ITEMS_REQUEST = 'FETCH_TOP_ITEMS_REQUEST';

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCES';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';

export const FETCH_MORE_ITEMS_SUCCESS = 'FETCH_MORE_ITEMS_SUCCESS';
export const FETCH_MORE_ITEMS_FAILURE = 'FETCH_MORE_ITEMS_FAILURE';
export const FETCH_MORE_ITEMS_REQUEST = 'FETCH_MORE_ITEMS_REQUEST';
export const SET_DISABLE = 'SET_DISABLE';

export const CHANGE_VALUE = 'CHANGE_VALUE';
export const OPEN_SEARCH = 'OPEN_SEARCH';
export const START_SEARCH = 'START_SEARCH';
export const CLOSE_SEARCH = 'CLOSE_SEARCH';

export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';
export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const CHANGE_FORM_VALUE = 'CHANGE_FORM_VALUE';
export const CLEAR_FORM_VALUES = 'CLEAR_FORM_VALUES';

export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';
export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST';
export const SET_INITIAL_ORDER_STATE = 'SET_INITIAL_ORDER_STATE';
